name: 'Terraform Deploy Workflow'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  package-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ai-content-generator-bart/backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt -t backend

  terraform:
    runs-on: ubuntu-latest
    needs: [package-backend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_gemini_api_key: ${{ secrets.GEMINI_API_KEY }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve